### ISSUE TITLE
SipMessage.createResponse(responseCode) should set the initial line based on responseCode 

### ISSUE THREAD

**Issue by demian0311** [aboutsip/sipstack#1]
I can call `createResponse` but it doesn't set the initial line based on the `responseCode`.  Like I might do a `sipMessage.createResponse(302)` the initial line might say `302 OK` instead of `302 Moved Temporarily`.  I have some ugly code in my app that fixes it by dumping it all to a string and then re-parsing it into a SipResponse.

If you welcome pull requests I could look into it as well.

Thanks for doing this project.  Great stuff!

**Comment by jonbo372** [comment]
Ah, good point!

And absolutely, pull requests are more than welcome and highly encouraged!

/Jonas

**Comment by jonbo372** [comment]
I have now fixed that issue in pkts.io here: https://github.com/aboutsip/pkts/commit/408c521b1e8c1d1c5acd860cbb1f827df62d205c

I'm going to have to build a new release and updates sipstack.io/pom.xml to that new release, which I will get around to later tonight. In the mean time, you can always check out pkts.io and reference the snapshot in the sipstack.io if you prefer.

**Comment by demian0311** [comment]
Very cool, I'll try it out soon.

Demian L. Neidetcher | neidetcher.com

**Comment by jonbo372** [comment]
Also released a new version of sipstack.io - 0.1.1 so please include that in your pom.

**Comment by demian0311** [comment]
Updated gradle and tested with 0.1.1.  Works great.  I was able to remove ~100 lines of code (including tests).

Thanks!
