### ISSUE TITLE
getContentTypeHeader

### ISSUE THREAD

**Issue by stormning** [aboutsip/sipstack#4]
After using sipMessage.getContentTypeHeader() ,
then use sipMessage.toBuffer().toString()
I found the contentTypeHeader value is missing

**Comment by stormning** [comment]
io.pkts.packet.sip.header.impl.ContentTypeHeaderImpl#transferValue

**Comment by jonbo372** [comment]
Thanks for filing the issue. This is an issue with siplib in pkts.io. Moving the bug to that project.

https://github.com/aboutsip/pkts/issues/65
